version: '3'
services:
  backend:
    image: bid_backend
    ports:
      - "8081:8081"
    volumes:
      - /home/ubuntu/workspace/bid/backend/images:/app/src/main/resources/static/images
      - /home/ubuntu/workspace/bid/backend/logs:/app/logs
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}