version: '3'
services:
  backend:
    image: bid_backend:${TAG}
    ports:
      - "8081:8081"
    volumes:
      - /workspace/bid/backend/images:/static/images/
      - /workspace/bid/backend/logs:/logs
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}

  frontend:
    image: bid_frontend:${TAG}
    ports:
      - "5173:5173"
    volumes:
      - /workspace/bid/frontend/logs:/logs
    restart: unless-stopped