version: '3'
services:
  backend:
    image: bid_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://i10d208.p.ssafy.io:3306/bid
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: d208928!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_REDIS_HOST: i10d208.p.ssafy.io
      SPRING_REDIS_PORT: 6379