export const icons = {
  BACK: <img src="/src/assets/icon/back.png" />,
  SEARCH: <img src="/src/assets/icon/search.png" />,
  NOTIFY: <img src="/src/assets/icon/notify.png" />,
  DELETE: <img src="/src/assets/icon/delete.png" />,
  ARROW_RIGHT: <img src="/src/assets/icon/arrowRight.png" />,
  CAMERA: <img src="/src/assets/icon/camera.png" />,
  CAMERA_ROTATE: <img src="/src/assets/icon/camera.png" />,
  CAMERA_SLASH: <img src="/src/assets/icon/cameraSlash.png" />,
  CHAT: <img src="/src/assets/icon/chatsCircle.png" />,
  DOTS_THREE: <img src="/src/assets/icon/dotsThree.png" />,
  MICROPHONE: <img src="/src/assets/icon/microphone.png" />,
  MICROPHONE_SLASH: <img src="/src/assets/icon/microphoneSlash.png" />,
  SIGN_OUT: <img src="/src/assets/icon/signOut.png" />,
  USER: <img src="/src/assets/icon/user.png" />,
  VIDEO_CAMERA: <img src="/src/assets/icon/videoCamera.png" />,
};
