server:
  port: 8081

spring:
  profiles:
    active: local # 기본설정
    group:
      local:
        - db-local
        - auth-local
      server:
        - db-server
        - auth-server
    include:
      - db
      - oauth

  datasource:
    driver-class-name: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  data:
    mongodb:
      uri: ${db.uri}

    redis:
      host: ${db.redis.host}
      port: ${db.redis.port}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


springdoc: #swagger
  packages-to-scan: com.qzp.bid
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /bid-ui.html            # Swagger UI 경로 => localhost:8000/bid-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

jwt:
  header: Authorization
  secret: ${auth.tokenSecret}
  token-validity-time: ${auth.tokenExpirationMsec}
  token-refresh-time: ${auth.tokenExpirationMsec}
