#auth 설정
auth:
  whiteList: ENC(SgJQQGAOGGVgqocjx9c5r9TtTmOFICQ862r2TfpuxB3oxFOBpWetdPPBei1hdHv0W+IBCWkhP5DaswQ15DZEd8Ta/Us7C3M8d9PvHvxFrFpt+Ipe1/yQoNFMD5j7VLmrudZd8QiVae8csvRl+AAvStHLlvUOKlhQ6wYFYHfN22rc4gDgJmlJYmQFKxcqP4oOq1SRBW7Pj4yWJby4OIQWok/upwQlEFOQIUQaYMssbDw=)
jwt:
  header: Authorization
  secret: ENC(fv3uJfbrB/x6anJJ9WlWZcBGj/af5ty4Zl2aZOmNCE1zqLeiULB35sFwtMYcFaw2/oo1EQBMB9s=)
  token-access-time: ENC(XsKWqhfuxpvk2x0PWKAn+w==)
  token-refresh-time: ENC(XsKWqhfuxpvk2x0PWKAn+w==)


--- # local
spring:
  config:
    activate:
      on-profile: "auth-local"
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(PuOzCnHPlzXLtF2QNi8/df0LUXyrBx4hi8sIGs4/2iY=)
            client-secret: ENC(o16SuX8pfIhOy3RIEfkCcoaUGGVhYmPM)
            redirect-uri: ENC(NjmwS7RoEvMgsHGEL/BS2+SNuKjcGbh7rbsa9JwP00GFKAfrUBsoski2iFU/K/cd3EgBXb8sGMw=)
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
oauth:
  redirect:
    url: ENC(u6gdrDzvpe9miujoUu0DQeCCi78lVP1bDOpVjYzEgPJvFqriPDDbwSUulAEpWRTC)

--- # server
spring:
  config:
    activate:
      on-profile: "auth-server"
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ENC(PuOzCnHPlzXLtF2QNi8/df0LUXyrBx4hi8sIGs4/2iY=)
            client-secret: ENC(o16SuX8pfIhOy3RIEfkCcoaUGGVhYmPM)
            redirect-uri: ENC(vbEhEhdKFCezCSdNJqFjHJLbfwWYMebVctB98PQXrJ0aR970ueWVdmg81T1x65cRX7nCcgJgeUQaLgHGz164Mg==)
            authorization-grant-type: authorization_code
            scope:
              - email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
oauth:
  redirect:
    url: ENC(jc0M/FXchfIcBfGOKOWAOkLnhf3gP7zVzrXd0higs/cNX92S8qZGV4dmYPM0hKf2II8e0ELiHB0=)