#auth 설정
auth:
  whiteList: ENC(SgJQQGAOGGVgqocjx9c5r9TtTmOFICQ862r2TfpuxB3oxFOBpWetdPPBei1hdHv0W+IBCWkhP5DaswQ15DZEd8Ta/Us7C3M8d9PvHvxFrFpt+Ipe1/yQoNFMD5j7VLmrudZd8QiVae8csvRl+AAvStHLlvUOKlhQ6wYFYHfN22rc4gDgJmlJYmQFKxcqP4oOq1SRBW7Pj4yWJby4OIQWok/upwQlEFOQIUQaYMssbDw=)
jwt:
  header: Authorization
  secret: ENC(fv3uJfbrB/x6anJJ9WlWZcBGj/af5ty4Zl2aZOmNCE1zqLeiULB35sFwtMYcFaw2/oo1EQBMB9s=)
  token-access-time: ENC(XsKWqhfuxpvk2x0PWKAn+w==)
  token-refresh-time: ENC(XsKWqhfuxpvk2x0PWKAn+w==)
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

--- # local
spring:
  config:
    activate:
      on-profile: "auth-local"
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ENC(C1BmOi7lmh67oOzRMKHI3pnNIHfXljSE4HiMOVYMJpi5aO3ok3G1TWW4x1Tl7suB)
            redirect-uri: ENC(hHI41AUmy4Nss1sLWV5an1iCW7kzLc2h2ubXAUCnZ5INMBNwpkDV1R7ajFtAT2SbjcuGdW46Y59oumKo7858rw==)
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - account_email
          naver:
            client-name: naver
            client-id: ENC(PuOzCnHPlzXLtF2QNi8/df0LUXyrBx4hi8sIGs4/2iY=)
            client-secret: ENC(o16SuX8pfIhOy3RIEfkCcoaUGGVhYmPM)
            redirect-uri: ENC(SwOi0TZSqX4+pw1xt5W6PuNEVzzZ/BcYTD98Rhd1ZCOB2l+2V9UqGTsVRYs3LbKyc2y/3MBpeuIYDb2oARs+Ww==)
            authorization-grant-type: authorization_code
            scope:
              - email

--- # server
spring:
  config:
    activate:
      on-profile: "auth-server"
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ENC(C1BmOi7lmh67oOzRMKHI3pnNIHfXljSE4HiMOVYMJpi5aO3ok3G1TWW4x1Tl7suB)
            redirect-uri: ENC(DXQPeCU88Dui1O67yubOE3ymYp/uMpN6cu9yOwHF0STxcqA2uQpZndFcGWjojI6jdpubkwjaA8A=)
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - account_email
          naver:
            client-name: naver
            client-id: ENC(PuOzCnHPlzXLtF2QNi8/df0LUXyrBx4hi8sIGs4/2iY=)
            client-secret: ENC(o16SuX8pfIhOy3RIEfkCcoaUGGVhYmPM)
            redirect-uri: ENC(8EBYCxxHdMUUGkp+1++eJZCMfRMWQ77RPZ5ysufiTCTT1PK/2sfZnYYrhatBtGdZElgAep7tGGA=)
            authorization-grant-type: authorization_code
            scope:
              - email