spring:
  profiles:
    active: # 기본설정
      - local
    group:
      local:
        - db-local
      server:
        - db-server
    include:
      - db
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
