image:
  upload:
    path: ENC(UJ9KHk0zaPmTGtn3xEilqPTMJq/W7bXdMIKgAzyIOa5lSXf44ujTNlO/2owTM8hY)

openvidu:
  url: ENC(zkfpSttUESMN6dblo1TwQhAmN5d7FMi/CGBJY6JH+zKIIdtdYvcFXg==)
  secret: ENC(KNJHLpgF4riOznuzNsyIWkw5CUpH8KKc)

---

spring:
  config:
    activate:
      on-profile: db-local
  datasource:
    driver-class-name: ${local.db.driver}
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
  data:
    mongodb:
      uri: ENC(zuBqpIbmGLBMbWiazTrhIkmVcf4RtMST7s1v6tsBKwOLuOhM+sdEJQ==)
    redis:
      host: ENC(C675blAMcXOErgQJtRu5WlsHTHHyJs9q)
      port: ENC(BwBUkunc7Vr8OqDKfeNL/A==)
      username:
      password:
  web:
    resources:
      static-locations: ENC(kZNWgJkZKJ+PiHLC2n9WpVg9mzJnN6urv1WlU9aUWlA=)
---
spring:
  config:
    activate:
      on-profile: db-server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(7DfqZdhzkRV32UXb/ZjA+skUfnSDhhiH//tX+kO+BIGaZ4/izmpOeZh5nq7qiik5pa1BZrDVo2M=)
    username: ENC(BT+NxbhZyaZKv4odRrYrtAzIu6UhZYpl)
    password: ENC(XsxnNbWCt8rygqdJk1q41kHzQ9SRjWpe)
  data:
    mongodb:
      uri: ENC(TsP7R0yzpvmB+xnJZBIf6eoiDB6VQovxWB1PKx2TVUKe8L7MCw5Cz+2VpeKPJ752opX4/PSebewK8tVs308WqoLXbsuEiTiG3LBphcOvF6ml4O02/m3wMNFignOqsxwRG+typSCG/qyfoCkAm6MOE6Qiw4LOJEzw)

    redis:
      host: ENC(Rn5UFKpvFvo9QPC73lWnOe48t1FILQLfrhf+soOaz+Q=)
      port: ENC(1TrHMFwQn/O0BP6eIIXNwg==)
      username: ENC(480/GSaOYGTC5M7XUxKucQ==)
      password: ENC(BIPTRfDba7N0Mn2hnckGE+QzoR38SJXN)
  web:
    resources:
      static-locations: ENC(af+isBISwWfLhsxV2HlPBnawsKp0tRZGLZssUj0/ViP+2zk6h0tk3CYNugXmUeG6GPKeCNY8fkQ=)